# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blacklist.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62lacklist.proto\x12\tblacklist\"!\n\x13PutBlackListRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"\x13\n\x11PutBlackListReply\"*\n\x13\x42lockCountryRequest\x12\x13\n\x0b\x63ountryCode\x18\x01 \x01(\t\"\x13\n\x11\x42lockCountryReply\"\x15\n\x13GetBlackListRequest\" \n\x11GetBlackListReply\x12\x0b\n\x03ips\x18\x01 \x03(\t\"!\n\x13PutWhiteListRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"\x13\n\x11PutWhiteListReply2\xa2\x03\n\tBlacklist\x12N\n\x0cPutBlackList\x12\x1e.blacklist.PutBlackListRequest\x1a\x1c.blacklist.PutBlackListReply\"\x00\x12N\n\x0c\x42lockCountry\x12\x1e.blacklist.BlockCountryRequest\x1a\x1c.blacklist.BlockCountryReply\"\x00\x12P\n\x0cGetBlackList\x12\x1e.blacklist.GetBlackListRequest\x1a\x1c.blacklist.GetBlackListReply\"\x00\x30\x01\x12S\n\x11GetBlackListUnary\x12\x1e.blacklist.GetBlackListRequest\x1a\x1c.blacklist.GetBlackListReply\"\x00\x12N\n\x0cPutWhiteList\x12\x1e.blacklist.PutWhiteListRequest\x1a\x1c.blacklist.PutWhiteListReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blacklist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUTBLACKLISTREQUEST']._serialized_start=30
  _globals['_PUTBLACKLISTREQUEST']._serialized_end=63
  _globals['_PUTBLACKLISTREPLY']._serialized_start=65
  _globals['_PUTBLACKLISTREPLY']._serialized_end=84
  _globals['_BLOCKCOUNTRYREQUEST']._serialized_start=86
  _globals['_BLOCKCOUNTRYREQUEST']._serialized_end=128
  _globals['_BLOCKCOUNTRYREPLY']._serialized_start=130
  _globals['_BLOCKCOUNTRYREPLY']._serialized_end=149
  _globals['_GETBLACKLISTREQUEST']._serialized_start=151
  _globals['_GETBLACKLISTREQUEST']._serialized_end=172
  _globals['_GETBLACKLISTREPLY']._serialized_start=174
  _globals['_GETBLACKLISTREPLY']._serialized_end=206
  _globals['_PUTWHITELISTREQUEST']._serialized_start=208
  _globals['_PUTWHITELISTREQUEST']._serialized_end=241
  _globals['_PUTWHITELISTREPLY']._serialized_start=243
  _globals['_PUTWHITELISTREPLY']._serialized_end=262
  _globals['_BLACKLIST']._serialized_start=265
  _globals['_BLACKLIST']._serialized_end=683
# @@protoc_insertion_point(module_scope)
