# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import containers_pb2 as containers__pb2


class ContainersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamContainers = channel.unary_stream(
                '/containers.Containers/StreamContainers',
                request_serializer=containers__pb2.ContainersRequest.SerializeToString,
                response_deserializer=containers__pb2.ContainersReply.FromString,
                )
        self.GetContainers = channel.unary_unary(
                '/containers.Containers/GetContainers',
                request_serializer=containers__pb2.ContainersRequest.SerializeToString,
                response_deserializer=containers__pb2.ContainersReply.FromString,
                )


class ContainersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamContainers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamContainers,
                    request_deserializer=containers__pb2.ContainersRequest.FromString,
                    response_serializer=containers__pb2.ContainersReply.SerializeToString,
            ),
            'GetContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainers,
                    request_deserializer=containers__pb2.ContainersRequest.FromString,
                    response_serializer=containers__pb2.ContainersReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'containers.Containers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Containers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/containers.Containers/StreamContainers',
            containers__pb2.ContainersRequest.SerializeToString,
            containers__pb2.ContainersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/containers.Containers/GetContainers',
            containers__pb2.ContainersRequest.SerializeToString,
            containers__pb2.ContainersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
