# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containers.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontainers.proto\x12\ncontainers\"\x13\n\x11\x43ontainersRequest\"5\n\tContainer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\"<\n\x0f\x43ontainersReply\x12)\n\ncontainers\x18\x01 \x03(\x0b\x32\x15.containers.Container2\xaf\x01\n\nContainers\x12R\n\x10StreamContainers\x12\x1d.containers.ContainersRequest\x1a\x1b.containers.ContainersReply\"\x00\x30\x01\x12M\n\rGetContainers\x12\x1d.containers.ContainersRequest\x1a\x1b.containers.ContainersReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'containers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTAINERSREQUEST']._serialized_start=32
  _globals['_CONTAINERSREQUEST']._serialized_end=51
  _globals['_CONTAINER']._serialized_start=53
  _globals['_CONTAINER']._serialized_end=106
  _globals['_CONTAINERSREPLY']._serialized_start=108
  _globals['_CONTAINERSREPLY']._serialized_end=168
  _globals['_CONTAINERS']._serialized_start=171
  _globals['_CONTAINERS']._serialized_end=346
# @@protoc_insertion_point(module_scope)
