# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x12\tdashboard\"\x12\n\x10\x44\x61shboardRequest\"5\n\tContainer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\"U\n\x0e\x44\x61shboardReply\x12\x0b\n\x03ips\x18\x01 \x03(\t\x12(\n\ncontainers\x18\x02 \x03(\x0b\x32\x14.dashboard.Container\x12\x0c\n\x04logs\x18\x03 \x01(\t2e\n\tDashboard\x12X\n\x1aStreamDashboardInformation\x12\x1b.dashboard.DashboardRequest\x1a\x19.dashboard.DashboardReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DASHBOARDREQUEST']._serialized_start=30
  _globals['_DASHBOARDREQUEST']._serialized_end=48
  _globals['_CONTAINER']._serialized_start=50
  _globals['_CONTAINER']._serialized_end=103
  _globals['_DASHBOARDREPLY']._serialized_start=105
  _globals['_DASHBOARDREPLY']._serialized_end=190
  _globals['_DASHBOARD']._serialized_start=192
  _globals['_DASHBOARD']._serialized_end=293
# @@protoc_insertion_point(module_scope)
