"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import dashboard_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class DashboardStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    StreamDashboardInformation: grpc.UnaryStreamMultiCallable[
        dashboard_pb2.DashboardRequest,
        dashboard_pb2.DashboardReply,
    ]

class DashboardAsyncStub:
    StreamDashboardInformation: grpc.aio.UnaryStreamMultiCallable[
        dashboard_pb2.DashboardRequest,
        dashboard_pb2.DashboardReply,
    ]

class DashboardServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def StreamDashboardInformation(
        self,
        request: dashboard_pb2.DashboardRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[dashboard_pb2.DashboardReply], collections.abc.AsyncIterator[dashboard_pb2.DashboardReply]]: ...

def add_DashboardServicer_to_server(servicer: DashboardServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
