# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dashboard_pb2 as dashboard__pb2


class DashboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDashboardInformation = channel.unary_stream(
                '/dashboard.Dashboard/StreamDashboardInformation',
                request_serializer=dashboard__pb2.DashboardRequest.SerializeToString,
                response_deserializer=dashboard__pb2.DashboardReply.FromString,
                )


class DashboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamDashboardInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDashboardInformation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDashboardInformation,
                    request_deserializer=dashboard__pb2.DashboardRequest.FromString,
                    response_serializer=dashboard__pb2.DashboardReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashboard.Dashboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dashboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamDashboardInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dashboard.Dashboard/StreamDashboardInformation',
            dashboard__pb2.DashboardRequest.SerializeToString,
            dashboard__pb2.DashboardReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
