# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logs_pb2 as logs__pb2


class LogsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLogs = channel.unary_stream(
                '/logs.Logs/StreamLogs',
                request_serializer=logs__pb2.LogRequest.SerializeToString,
                response_deserializer=logs__pb2.LogReply.FromString,
                )
        self.GetLogs = channel.unary_stream(
                '/logs.Logs/GetLogs',
                request_serializer=logs__pb2.LogRequest.SerializeToString,
                response_deserializer=logs__pb2.LogReply.FromString,
                )


class LogsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=logs__pb2.LogRequest.FromString,
                    response_serializer=logs__pb2.LogReply.SerializeToString,
            ),
            'GetLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=logs__pb2.LogRequest.FromString,
                    response_serializer=logs__pb2.LogReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logs.Logs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/logs.Logs/StreamLogs',
            logs__pb2.LogRequest.SerializeToString,
            logs__pb2.LogReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/logs.Logs/GetLogs',
            logs__pb2.LogRequest.SerializeToString,
            logs__pb2.LogReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
