# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlogs.proto\x12\x04logs\"\x0c\n\nLogRequest\"\x1b\n\x08LogReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2k\n\x04Logs\x12\x32\n\nStreamLogs\x12\x10.logs.LogRequest\x1a\x0e.logs.LogReply\"\x00\x30\x01\x12/\n\x07GetLogs\x12\x10.logs.LogRequest\x1a\x0e.logs.LogReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGREQUEST']._serialized_start=20
  _globals['_LOGREQUEST']._serialized_end=32
  _globals['_LOGREPLY']._serialized_start=34
  _globals['_LOGREPLY']._serialized_end=61
  _globals['_LOGS']._serialized_start=63
  _globals['_LOGS']._serialized_end=170
# @@protoc_insertion_point(module_scope)
