# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmobile.proto\x12\x06mobile\"\x18\n\x16WireguardConfigRequest\".\n\x17WireguardConfigResponse\x12\x13\n\x0b\x62\x61se64Image\x18\x01 \x01(\t2_\n\x06Mobile\x12U\n\x12GetWireguardConfig\x12\x1e.mobile.WireguardConfigRequest\x1a\x1f.mobile.WireguardConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WIREGUARDCONFIGREQUEST']._serialized_start=24
  _globals['_WIREGUARDCONFIGREQUEST']._serialized_end=48
  _globals['_WIREGUARDCONFIGRESPONSE']._serialized_start=50
  _globals['_WIREGUARDCONFIGRESPONSE']._serialized_end=96
  _globals['_MOBILE']._serialized_start=98
  _globals['_MOBILE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
