# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rules.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brules.proto\x12\x05rules\"#\n\x12PutNewRulesRequest\x12\r\n\x05rules\x18\x01 \x01(\t\"\x12\n\x10PutNewRulesReply\"\'\n\x14PutNewFiltersRequest\x12\x0f\n\x07\x66ilters\x18\x01 \x01(\t\"\x14\n\x12PutNewFiltersReply\"\x11\n\x0fGetRulesRequest\"/\n\rGetRulesReply\x12\r\n\x05rules\x18\x01 \x01(\t\x12\x0f\n\x07\x66ilters\x18\x02 \x01(\t2\xee\x01\n\x05Rules\x12L\n\x14PutNewDetectionRules\x12\x19.rules.PutNewRulesRequest\x1a\x17.rules.PutNewRulesReply\"\x00\x12R\n\x16PutNewDetectionFilters\x12\x1b.rules.PutNewFiltersRequest\x1a\x19.rules.PutNewFiltersReply\"\x00\x12\x43\n\x11GetDetectionRules\x12\x16.rules.GetRulesRequest\x1a\x14.rules.GetRulesReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rules_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUTNEWRULESREQUEST']._serialized_start=22
  _globals['_PUTNEWRULESREQUEST']._serialized_end=57
  _globals['_PUTNEWRULESREPLY']._serialized_start=59
  _globals['_PUTNEWRULESREPLY']._serialized_end=77
  _globals['_PUTNEWFILTERSREQUEST']._serialized_start=79
  _globals['_PUTNEWFILTERSREQUEST']._serialized_end=118
  _globals['_PUTNEWFILTERSREPLY']._serialized_start=120
  _globals['_PUTNEWFILTERSREPLY']._serialized_end=140
  _globals['_GETRULESREQUEST']._serialized_start=142
  _globals['_GETRULESREQUEST']._serialized_end=159
  _globals['_GETRULESREPLY']._serialized_start=161
  _globals['_GETRULESREPLY']._serialized_end=208
  _globals['_RULES']._serialized_start=211
  _globals['_RULES']._serialized_end=449
# @@protoc_insertion_point(module_scope)
