"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RoleEnum:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RoleEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RoleEnum.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADMIN: _RoleEnum.ValueType  # 0
    CAN_INVITE: _RoleEnum.ValueType  # 1
    CAN_MANAGE_IP: _RoleEnum.ValueType  # 2
    CAN_READ_IP: _RoleEnum.ValueType  # 3
    CAN_READ_LOGS: _RoleEnum.ValueType  # 4
    CAN_MANAGE_CONFIGURATION: _RoleEnum.ValueType  # 5
    CAN_READ_SERVICES: _RoleEnum.ValueType  # 6

class RoleEnum(_RoleEnum, metaclass=_RoleEnumEnumTypeWrapper): ...

ADMIN: RoleEnum.ValueType  # 0
CAN_INVITE: RoleEnum.ValueType  # 1
CAN_MANAGE_IP: RoleEnum.ValueType  # 2
CAN_READ_IP: RoleEnum.ValueType  # 3
CAN_READ_LOGS: RoleEnum.ValueType  # 4
CAN_MANAGE_CONFIGURATION: RoleEnum.ValueType  # 5
CAN_READ_SERVICES: RoleEnum.ValueType  # 6
global___RoleEnum = RoleEnum

@typing_extensions.final
class SignInSignUpRequest(google.protobuf.message.Message):
    """The SignInSignUpRequest message is used for the SignIn and SignUp operations."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    email: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "password", b"password"]) -> None: ...

global___SignInSignUpRequest = SignInSignUpRequest

@typing_extensions.final
class UserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    message: builtins.str
    token: builtins.str
    @property
    def user(self) -> global___UserDto: ...
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        token: builtins.str = ...,
        user: global___UserDto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "token", b"token", "user", b"user"]) -> None: ...

global___UserResponse = UserResponse

@typing_extensions.final
class EmptyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___EmptyRequest = EmptyRequest

@typing_extensions.final
class EmptyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___EmptyResponse = EmptyResponse

@typing_extensions.final
class PasswordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: builtins.int
    password: builtins.str
    def __init__(
        self,
        *,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password"]) -> None: ...

global___PasswordRequest = PasswordRequest

@typing_extensions.final
class EmailRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email"]) -> None: ...

global___EmailRequest = EmailRequest

@typing_extensions.final
class InviteUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    email: builtins.str
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___RoleEnum.ValueType]: ...
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        roles: collections.abc.Iterable[global___RoleEnum.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "roles", b"roles"]) -> None: ...

global___InviteUserRequest = InviteUserRequest

@typing_extensions.final
class ChangeRightsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    email: builtins.str
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___RoleEnum.ValueType]: ...
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        roles: collections.abc.Iterable[global___RoleEnum.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "roles", b"roles"]) -> None: ...

global___ChangeRightsRequest = ChangeRightsRequest

@typing_extensions.final
class UserDto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    ACTIVATED_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    NIGHTMODE_FIELD_NUMBER: builtins.int
    id: builtins.str
    email: builtins.str
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___RoleEnum.ValueType]: ...
    activated: builtins.bool
    language: builtins.str
    nightMode: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        email: builtins.str = ...,
        roles: collections.abc.Iterable[global___RoleEnum.ValueType] | None = ...,
        activated: builtins.bool = ...,
        language: builtins.str = ...,
        nightMode: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["activated", b"activated", "email", b"email", "id", b"id", "language", b"language", "nightMode", b"nightMode", "roles", b"roles"]) -> None: ...

global___UserDto = UserDto

@typing_extensions.final
class GetUsersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserDto]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[global___UserDto] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["users", b"users"]) -> None: ...

global___GetUsersResponse = GetUsersResponse

@typing_extensions.final
class ActivateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    token: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "token", b"token"]) -> None: ...

global___ActivateUserRequest = ActivateUserRequest

@typing_extensions.final
class ActivateUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    token: builtins.str
    @property
    def user(self) -> global___UserDto: ...
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        user: global___UserDto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["token", b"token", "user", b"user"]) -> None: ...

global___ActivateUserResponse = ActivateUserResponse

@typing_extensions.final
class ChangeLanguageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: builtins.int
    language: builtins.str
    def __init__(
        self,
        *,
        language: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["language", b"language"]) -> None: ...

global___ChangeLanguageRequest = ChangeLanguageRequest

@typing_extensions.final
class UserLanguageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAN_FIELD_NUMBER: builtins.int
    lan: builtins.str
    def __init__(
        self,
        *,
        lan: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lan", b"lan"]) -> None: ...

global___UserLanguageResponse = UserLanguageResponse

@typing_extensions.final
class HistoryEntryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.str
    """ID de l'entrée d'historique créée"""
    status: builtins.str
    """Par exemple, "success" ou "error" """
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "status", b"status"]) -> None: ...

global___HistoryEntryResponse = HistoryEntryResponse

@typing_extensions.final
class GetHistoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHistoryRequest = GetHistoryRequest

@typing_extensions.final
class GetHistoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___HistoryEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___GetHistoryResponse = GetHistoryResponse

@typing_extensions.final
class HistoryEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    ACTIONTYPE_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    id: builtins.str
    date: builtins.str
    actionType: builtins.str
    userId: builtins.str
    description: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        date: builtins.str = ...,
        actionType: builtins.str = ...,
        userId: builtins.str = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["actionType", b"actionType", "date", b"date", "description", b"description", "id", b"id", "userId", b"userId"]) -> None: ...

global___HistoryEntry = HistoryEntry

@typing_extensions.final
class NightModeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NIGHTMODE_FIELD_NUMBER: builtins.int
    nightMode: builtins.bool
    def __init__(
        self,
        *,
        nightMode: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["nightMode", b"nightMode"]) -> None: ...

global___NightModeRequest = NightModeRequest

@typing_extensions.final
class UserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UserRequest = UserRequest
